### ISSUE TITLE
build anp/konnectivity into cluster-proxy image

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/cluster-proxy#18]
There is no upstream anp image yet. We should build a binary and add it into cluster-proxy image

/assign @xuezhaojun

**Comment by qiujian16** [comment]
@xuezhaojun would you also check if we can specify anp images when starting cluster-proxy?

**Comment by xuezhaojun** [comment]
> @xuezhaojun would you also check if we can specify anp images when starting cluster-proxy?

Yes, we can. The image is set by: https://github.com/open-cluster-management-io/cluster-proxy/blob/38c2abc379a66524036ba933be3b7d3e8e425028/charts/cluster-proxy/values.yaml#L9

If we change this value, it will use another image.

**Comment by xuezhaojun** [comment]
Already Done in latest version /close
