### ISSUE TITLE
proxyagent didn't registration but the `Available` status shows `True`

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/cluster-proxy#44]
Platform: macOS + Kind
Version: the latest code

What I have done:

After the cluster-proxy is installed, I found the addon installed successfully on the hub:
```
➜  cluster-proxy-test-env k get managedclusteraddons.addon.open-cluster-management.io -A                        
NAMESPACE   NAME            AVAILABLE   DEGRADED   PROGRESSING
cluster1    cluster-proxy   True 
```

But, on the managed cluster, the logs of addon-agent continuously shows error msg as the following:
```
E0104 11:16:21.900558       1 portforward.go:79] error handling connection: pods is forbidden: User "open-cluster-management:cluster-proxy:addon-agent" cannot list resource "pods" in API group "" in the namespace "open-cluster-management-addon" 
```

It seems we should grant proper permission for User "open-cluster-management:cluster-proxy:addon-agent", but I checked the code and found there is no relevant process yet.

Would you mind taking a look at this one?  @yue9944882

**Comment by yue9944882** [comment]
@xuezhaojun sure, will TAL

/assign

**Comment by yue9944882** [comment]
@xuezhaojun interestingly in fact, we did missed RBAC permission for pod listing and port-forwarding for the addon agents, but the e2e tests can oddly work w/o that permission..

**Comment by yue9944882** [comment]
https://github.com/open-cluster-management-io/cluster-proxy/blob/22682dff375e16e1118e8ada0132e78c1ad17094/controllers/manifests.go#L183-L186

@xuezhaojun the missing permission should be set up by the addon-manager, did you upgrade your addon-manager to the latest version (i.e. v1.0.2)?

**Comment by xuezhaojun** [comment]
I think the reason may be https://github.com/open-cluster-management-io/cluster-proxy/blob/22682dff375e16e1118e8ada0132e78c1ad17094/cmd/addon-agent/main.go#L28
Although pods are running in `open-cluster-management-proxy` namespace, but the default flag value at addon-agent is `open-cluster-management-addon`

**Comment by xuezhaojun** [comment]
The root reason is I install cluster-proxy into `open-cluster-management-proxy` install of `open-cluster-management-addon`. 

There is a little conflict in `readme.md` as the following:

https://github.com/open-cluster-management-io/cluster-proxy/blob/22682dff375e16e1118e8ada0132e78c1ad17094/README.md#L53-L60


After installation, the pods are running in the `open-cluster-management-addon` namespace, but in the document it checks pods in `open-cluster-management-cluster-proxy` namespace.

**Comment by xuezhaojun** [comment]
Another thinking is, maybe we can add a flag after this line:

https://github.com/open-cluster-management-io/cluster-proxy/blob/22682dff375e16e1118e8ada0132e78c1ad17094/pkg/addon/agent/agent.go#L292

```
addonAgentArgs := []string{
		"--hub-kubeconfig=/etc/kubeconfig/kubeconfig",
		"--cluster-name=" + clusterName,
                 "--proxy-server-namespace=proxyConfig.Spec.ProxyServer.Namespace" # add this
	}
```

This will make sure addon-agent access the right namespace no matter what namespace we specified.

**Comment by yue9944882** [comment]
ah yes, i think we should call this a bug
